services:
  globetalk-front:
    build:
      context: ../globetalk-front  # Path relative to where you run docker-compose
      dockerfile: Dockerfile  # Assuming Dockerfile is in the root of globetalk-front
    env_file:
      - ../globetalk-front/.env.production  # Adjust path as necessary

  globetalk-back:
    build:
      context: ./  # Adjust this path to the backend directory's name
      dockerfile: Dockerfile  # Assuming Dockerfile is in the root of globetalk-back
    volumes:
      - certdata:/etc/letsencrypt
      - ./nginx/conf:/etc/nginx/conf.d
    env_file:
      - ./.env.production  # Adjust path as necessary
    restart: always
    depends_on:
      - mongo

  nginx:
    build:
      context: ./  # Adjust this path to the backend directory's name
      dockerfile: Dockerfile  # Assuming Dockerfile is in the root of globetalk-back
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - globetalk-back
      - globetalk-front

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=globetalk
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: