version: '3.8'

services:
  frontend:
    image: globetalk-front
    container_name: globetalk-front
    build:
      context: ../globetalk-front  # Path relative to where you run docker-compose
      dockerfile: Dockerfile  # Assuming Dockerfile is in the root of globetalk-front
    env_file:
      - ../globetalk-front/.env.production  # Adjust path as necessary
    networks:
      - peterkapena

  backend:
    image: globetalk-back
    container_name: globetalk-back
    build:
      context: ./  # Adjust this path to the backend directory's name
      dockerfile: Dockerfile  # Assuming Dockerfile is in the root of globetalk-back
    env_file:
      - ./.env.production  # Adjust path as necessary
    restart: always
    networks:
      - peterkapena

networks:
  peterkapena:
    external: true
