services:
  globetalk-front:
    build:
      context: ../globetalk-front
      dockerfile: Dockerfile
    env_file:
      - ../globetalk-front/.env.production
    depends_on:
      - globetalk-back

  globetalk-back:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.production 
    restart: always
    depends_on:
      - mongo

  mtm-back:
    build:
      context: ../mtm-back
      dockerfile: Dockerfile
    env_file:
      - ../mtm-back/.env.production
    depends_on:
      - mongo

  mtm-front:
    build:
      context: ../mtm_front
      dockerfile: Dockerfile
    env_file:
      - ../mtm_front/.env.production
    depends_on:
      - mtm-back

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certdata:/etc/letsencrypt
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - globetalk-back
      - globetalk-front

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=globetalk
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  certdata:
