services:
  # globetalk-front:
  #   build:
  #     context: ../globetalk-front  # Path relative to where you run docker-compose
  #     dockerfile: Dockerfile  # Assuming Dockerfile is in the root of globetalk-front
  #   env_file:
  #     - ../globetalk-front/.env.production  # Adjust path as necessary
  #   networks:
  #     - peterkapena

  globetalk-back:
    build:
      context: ./  # Adjust this path to the backend directory's name
      dockerfile: Dockerfile  # Assuming Dockerfile is in the root of globetalk-back
    env_file:
      - ./.env.production  # Adjust path as necessary
    restart: always
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ngix.default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - globetalk-back

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=globetalk
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: